opium/app.ml

Previously the Response_helper module ignored any custom HTTP
headers passed through to Json, XML or HTML responses.  We now
preserve these and just add a Content-Type header.

Allow non-HTML Opium responses to add custom HTTP headers

---

_oasis
opam
opium/static_serve.ml
opium/static_serve.mli

This uses the `magic-mime` library to detect the filename and
generate a sensible MIME type from the `mime.types` database.
It is particularly important to generate these for Internet Explorer
support, since IE10 seems to ignore `.css` files that do not send
an appropriate MIME header.  With this patch, IE10 rendering works
great using an Opium rendering stack.

Generate Content-Type headers for static file serving

---

opium/cookie.ml
opium/cookie.mli

This patch adds a `?expiration : Cohttp.Cookie.expiration` parameter to `Cookie.set` and `Cookie.set_cookies` functions.
This works by using a new Env for response cookies (before, the same Env than request cookies was uesd), with a cookie of type `(string * string * Cohttp.Cookie.expiration)`.
This patch doesn't break `Cookie` interface since the new parameter is optional, and default to `Session`.

Add expiration parameter to cookies

---

opium/app.ml
opium/app.mli
rock/opium_rock.ml
rock/opium_rock.mli

This patch adds the following options to enable SSL when starting the server:
```
-s VAL, --ssl-cert=VAL
SSL certificate file
-k VAL, --ssl-key=VAL
SSL key file
```

Add SSL options to server

---

.merlin
OMakefile
README.md
examples/auth_middleware.ml
examples/exit_hook_example.ml
examples/hello_world.ml
examples/hello_world_basic.ml
examples/hello_world_html.ml
examples/middleware_ua.ml
examples/read_json_body.ml
examples/sample.ml
examples/static_serve_override.ml
examples/uppercase_middleware.ml
lib_test/routes.ml
opium/opium_app.ml
opium/opium_app.mli
opium/opium_debug.ml
opium/opium_static_serve.ml
opium_kernel/opium_cookie.ml
opium_kernel/opium_cookie.mli
opium_kernel/opium_misc.ml
opium_kernel/opium_rock.ml
opium_kernel/opium_rock.mli
opium_kernel/opium_route.ml
opium_kernel/opium_router.ml
opium_kernel/opium_umap.ml

This is currently *work in progress*, do not merge yet. Purpose: solve #40.
I added a `opium_kernel/opium_umap` (temporarily) to discuss the API and get one that works sufficiently well. We will fork it into its own library once we reach agreement on its interface (it is already a functor).
`Opium_misc`  now contains some utils to replace parts of `core_kernel` (missing functions, etc.). I also removed the `Info` stuff and replaced it with mere strings. I kept the sexplib stuff (a bit annoying to rewrite though). Tests do not compile yet.

remove core_kernel

---

opium/opium_app.ml

Command line options about ssl will always write over `app.ssl`. So when it has already been set by `App.ssl` function call, but not given any information through command line, the ssl will not be enabled (evaluated to `None` eventually).
In this patch, preference is given to command line option when both are not `None`.

enable ssl when it's set only through api but not cli

---

opium_kernel/cookie.ml
opium_kernel/cookie.mli

Also, only cookie values should be percent-decoded. The keys should be
using the safe alphabet as per the spec.
This fixes issue #57.

Do not use or assume Base 64 encoding of cookies

---

examples/sample.ml
opium.opam
opium/jbuild

Lwt_log is deleted from lwt >= 4.0.0, adding lwt_log to the dependencies allows opium to compile with lwt 4.1.0.

Add lwt_log to dependencies

---

opium_kernel/cookie.ml
opium_kernel/cookie.mli

- Expose all the HTTP cookie directives, not just expiration
- Remove the defaults from `set_cookies` and use `Set_cookie_hdr.make`'s defaults. This is the same for the expiration (both are `Session`), but path is no longer fixed/defaulted to `/`.
- Use `Set_cookie_hdr.t` as the internal representation of the cookie used by the middleware as it has all the fields we want and a sexp representation.
NB: encoding of the cookie data is now done when adding to the Env rather than at the point of serialisation - this might actually make debugging a bit easier as it will be clearer that opium is encoding itself rather than something lower level? But happy to change this back if that seems sensible.

Expose all cookie directives

---

opium.opam
opium/jbuild
opium/static_serve.ml

I noticed the travis build was failing on ocaml 4.03 due to `String.split_on_char` (introduced in `4.04`) . As `stringext` is already a transitive dependency I've added it explicitly and used that to keep compatibility with 4.03.

String split fix for ocaml < 4.04

---

README.cpp.md
README.md
examples/dune
opium.opam
opium_kernel.opam

I was having some issues setting up the `cow` and `omd` when using esy. While looking into it i noticed that `cow` isn't really being used anywhere. 
Signed-off-by: Anurag Soni <anurag@sonianurag.com>

Remove `cow` from deps as it isn't used anywhere

---

README.cpp.md
README.md
examples/README.md
examples/hello_world_html.ml

Followup to https://github.com/rgrinberg/opium/issues/124#issuecomment-569076800 
This directs readers to the `examples` directory from within the documentation section of the main readme and adds a readme to the examples directory.
It also updates the instructions around building and running the examples to use dune.

Add README.md for examples

---

opium/app.mli

Small documentation add. The main intent is to point users in the right place when they search for "form data".

Add documentation for urlencoded_pairs_of_body

---

examples/hello_world.ml
opium/app.ml
opium/app.mli
opium/opium.ml

feature: allow overriding 404 handler

---

README.cpp.md
README.md

I've completed (the initial draft of) a tutorial on building a small, but relatively feature complete tutorial based around Opium: https://shonfeder.gitlab.io/ocaml_webapp/
The tutorial aims to lead a reader with some OCaml familiarity from installing an OCaml dev environment up to a working app using Opium, Caqti (for PostgreSQL), and Tyxml.
From discussions with @anuragsoni, it sounds like there may be interest in linking this tutorial from the README here, so I've opened this PR to propose the addition. If the proposal is acceptable, I hope the review of this PR might include a quick glance at the linked tutorial to ensure the usage detailed there fits with expected Opium usage.
Commit a60d91f is an unrelated followup that resulted from running the make rule on the README.

Link OCaml Webapp Tutorial from README 

---

examples/hello_world.ml
opium/app.ml
opium/app.mli

Second attempt at supporting streams. Instead of exposing
the underlying type, expose an api which gives the user
a push function where they can push strings.

Expose a push function for streams

---

dune-project
opium.opam
opium_kernel.opam
opium_kernel/src/allow_cors.ml
opium_kernel/src/opium_kernel.ml
opium_kernel/src/opium_kernel.mli
opium_kernel/test/dune
opium_kernel/test/middleware_allow_cors.ml

This PR adds a middleware to manage CORS headers.
It adds the appropriate headers for regular requests and handles [preflight requests](https://developer.mozilla.org/en-US/docs/Glossary/preflight_request).
It depends on #162, but I can refactor if you prefer not to merge it.

Add CORS middleware

---

opium/app.ml
opium/app.mli

Currently the server binds to `inet_addr_loopback` (_i.e._ localhost). This PR adds support for setting a custom host when starting the app.
The host can be set similarly to the port with a builder option:
```ocaml
App.empty
|> App.host "localhost"
|> App.port port
...
|> App.start
```
By default the host is set to `0.0.0.0`.

Allow using a custom host to bind the server.

---

.github/workflows/format.yml
.github/workflows/test.yml
dune-project
opium.opam
opium_kernel.opam

#152 moved `magic-mime` dependency to `opium_kernel`, but the opam files didn't reflect this. This resulted in a compilation error when pinning `opium_kernel` because of the missing dependency.

Add magic mime opium kernel

---

opium_kernel/src/debugger.ml
opium_kernel/src/opium_kernel.mli
opium_kernel/src/rock.ml
opium_kernel/src/server_connection.ml

As discussed, I extracted the early response part of #149 into a single PR.
The reason for adding this is that some middleware might want to take control of the request flow and decide to return the response early. This is the case for instance for an error handler, where once the error is caught and the response is generated, we most likely do not want other middleware to mess with the response.
The implementation is inspired by https://github.com/ocamllabs/ocaml-effects-tutorial.
I've been trying to think of other solutions, but I can't think of one that wouldn't add a lot of overhead. I'm happy to try other implementations if you have any idea 🙂

Add a Halt exception to allow early responses

---

.github/workflows/ci.yml
.github/workflows/format.yml

The way ocaml-setup is implemented prevents us from using caching on different versions of OCaml so merging #183 broke the CI on master.
I'm experimenting with changes to `setup-ocaml` to fix the issue, otherwise, I'll comment out the caching parts of the workflow.

Fix broken CI/CD

---

opium/opium.ml
opium_kernel/src/opium_kernel.ml
opium_kernel/src/opium_kernel.mli

It should only be referred to as Hmap0 when we need to differentiate it
with the toplevel Hmap module.

Rename Hmap to Hmap0 in public interface

---

CHANGES.md
README.md
dune-project
opium.opam
opium_kernel.opam

From https://github.com/ocaml/opam-repository/pull/17577

Add an upper bound to Cohttp

---

CHANGES.md
opium/src/opium.mli

Did I forget anything in the changelog?
Everyone seemed ok with releasing as-is, but just in case you think one of these tasks should be done before releasing, here are the todos I had based on our previous conversations:
I would feel a bit better releasing if we had more tests, but I've been using the master branch in production for a while now and did not notice any issue, so not a blocker IMO, but let me know how you feel about that.

Prepare release

---

opium/src/app.ml
opium/src/app.mli

httpaf based opium doesn't work with lwt_ssl/ocaml-tls at the moment.
Removing cli params that talk about ssl should prevent any confusion about this. (see: #230)

remove references to ssl

---

dune-project
opium-testing.opam
opium-testing.opam.locked
opium.opam
opium.opam.locked
rock.opam
rock.opam.locked

Should enable us to `opam install --with-doc opium`.

Add odoc with-doc dependency

---

example/static_serve/main.ml

This PR removes the comment in `example/static_serve/main.ml` which does not reflect what the program actually does.
I think the mentioned example is worth having, though.

static_serve: comment does not reflect the code

---

.github/workflows/ci.yml
.vscode/settings.json
README.md
example/hello_world/dune
example/hello_world/main.ml
example/user_auth/README.md
example/user_auth/dune
example/user_auth/main.ml
opium/src/auth.ml
opium/src/auth.mli
opium/src/middlewares/middleware_basic_auth.ml
opium/src/middlewares/middleware_basic_auth.mli
opium/src/opium.ml
opium/src/opium.mli
opium/src/request.ml
opium/src/request.mli

This PR adds a `basic_auth` middleware to protect handlers with an authentication mechanism.
It also adds an `Auth` module with functions to encode/decode `Authorization` header values.
The `basic_auth` middleware has type
```ocaml
val basic_auth
:  ?unauthorized_handler:Rock.Handler.t
-> key:'a Context.key
-> realm:string
-> auth_callback:(username:string -> password:string -> 'a option)
-> unit
-> Rock.Middleware.t
```
I believe it is flexible enough and will allow users to build their own authentication logic, without having to deal with the boilerplate logic.
**TODO**

Basic auth middleware

---

CHANGES.md
opium/src/cookie.ml
opium/test/cookie.ml
opium/test/dune

I am not sure how many spaces we should allow between the key value pairs in the `Cookie` header, but this change fixes handling of multiple cookies with how the most common browser do it I think.

Fix cookie header parsing by trimming cookie key

---

CHANGES.md
opium/src/route.ml
opium/test/route.ml

The routes `"/**"` and `"/*/*/*"` when matched on the url `"/1/2/3"` will return splat values `["3"; "2"; "1"]`. This PR undoes the reversing so the splat values are `["1"; "2"; "3"]` as you would expect.

Don't reverse splat matches

---

CHANGES.md
opium/src/route.ml
opium/test/route.ml

This fixes #249 and adds tests.
The splat values are in reverse order, and I think that's a mistake. However, that's the existing behavior of single splats. I will make a separate PR for this.

Fix full splat `**`

---

opium/doc/index.mld

With this line in the code, I got the following error:
```
10 |   let open App in
^^^^^^^^
Error (warning 33 [unused-open]): unused open Opium.App.
```

Remove unused open from example

---

CHANGES.md
opium/src/middlewares/middleware_static.ml
opium/src/middlewares/middleware_static.mli
opium/src/middlewares/middleware_static_unix.ml
opium/src/middlewares/middleware_static_unix.mli
opium/src/opium.mli

This PR changes the static middlewares' ETag argument from
`?etag_of_fname:(string -> string option)` to
`?etag_of_fname:(string -> string option Lwt.t)`.
This change was proposed in #265.

Get ETag as LWT promise

---

README.md

One of these script was mislabled at `shell` when it wasn’t a shell script but a shell session. The following block while it is technically JSON, is more appropriately the stdout from cURL in that shell session.

move shell session blocks to appropriate syntax
